/** @vitest-environment jsdom */
import {act} from "react";import {createRoot} from "react-dom/client";import {afterEach,beforeEach,expect,it,vi} from "vitest";
const mocks=vi.hoisted(()=>{const engine={engineUrl:"http://engine.test",setTokenProvider:vi.fn(),isHealthy:async()=>true,discover:async()=>"http://engine.test",getPlatformContext:async()=>({}),listTools:async()=>[],getVersion:async()=>"x",getSystemInfo:async()=>({}),configureCloudSync:vi.fn(),reconfigureCloudSync:vi.fn(),connectWebSocket:vi.fn(),disconnect:vi.fn(),on:()=>()=>undefined,prepareSessionTransition:async()=>({status:"aligned",origin:"x",generation:"g",credentialRevision:0,subject:"actor-a"}),cloudHeartbeat:async()=>undefined};return{engine,listener:undefined as any,session:{user:{id:"actor-a"},access_token:"daemon"},context:{revision:1,isCurrent:()=>true,engineOrigin:"x",engineGeneration:"g"}};});
vi.mock("@/lib/api",()=>({engine:mocks.engine}));vi.mock("@/lib/custodian",()=>({getAuthedSession:async()=>mocks.session}));vi.mock("@/lib/native-vault-auth",()=>({resolveNativeVaultEngineAccessToken:async()=>"daemon",isNativeVaultHostRevisionCurrent:()=>true,nativeVaultEngineTransitionContext:(id:string)=>id==="actor-a"?mocks.context:null,subscribeNativeVaultHostEvents:(cb:any)=>{mocks.listener=cb;return()=>undefined;}}));vi.mock("@/lib/sidecar",()=>({ENGINE_STARTUP_TIMEOUT_SECONDS:1,isTauri:()=>false,startSidecar:vi.fn(),stopSidecar:vi.fn(),waitForOwnedEngine:vi.fn()}));vi.mock("@/lib/platformCtx",()=>({initPlatformCtx:vi.fn()}));vi.mock("@/lib/background-tasks",()=>({startBackgroundTasks:vi.fn(),stopBackgroundTasks:vi.fn()}));vi.mock("@/hooks/use-window-leader",()=>({useWindowLeader:()=>true}));vi.mock("@/hooks/use-client-log",()=>({emitClientLog:vi.fn()}));import {useEngine} from "./use-engine";
let hook: ReturnType<typeof useEngine>;
function Subject(){ hook=useEngine(); return null; }
let root:any;beforeEach(async()=>{mocks.context.revision=1;(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;root=createRoot(document.createElement("div"));await act(async()=>root.render(<Subject/>));});afterEach(async()=>act(async()=>root.unmount()));
it("reopens a failed socket without repeating the accepted configuration", async()=>{
  mocks.engine.reconfigureCloudSync.mockClear(); mocks.engine.connectWebSocket.mockClear(); mocks.context.revision=2;
  mocks.engine.connectWebSocket.mockRejectedValueOnce(new Error("socket unavailable"));
  act(()=>mocks.listener({session:mocks.session,revision:2,completion:Promise.resolve({accepted:true})}));
  await vi.waitFor(()=>expect(mocks.engine.reconfigureCloudSync).toHaveBeenCalledTimes(1));
  await act(async()=>{ await hook.retryAccountConnection(); });
  expect(mocks.engine.reconfigureCloudSync).toHaveBeenCalledTimes(1);
  expect(mocks.engine.connectWebSocket).toHaveBeenCalledTimes(2);
});
it("failed new actor disconnects and performs no cloud request",async()=>{mocks.engine.disconnect.mockClear();mocks.engine.configureCloudSync.mockClear();act(()=>mocks.listener({session:{user:{id:"actor-b"}},revision:1,completion:Promise.resolve({accepted:false})}));expect(mocks.engine.disconnect).toHaveBeenCalled();await Promise.resolve();expect(mocks.engine.configureCloudSync).not.toHaveBeenCalled();});
it("refresh waits for completion then reconfigures and reconnects",async()=>{let release!:(value:any)=>void;const pending=new Promise<any>(r=>release=r);mocks.engine.reconfigureCloudSync.mockClear();mocks.engine.connectWebSocket.mockClear();mocks.context.revision=2;act(()=>mocks.listener({session:mocks.session,revision:2,completion:pending}));await Promise.resolve();expect(mocks.engine.reconfigureCloudSync).not.toHaveBeenCalled();await act(async()=>{release({accepted:true});await new Promise(resolve=>setTimeout(resolve,0));});expect(mocks.engine.reconfigureCloudSync).toHaveBeenCalled();expect(mocks.engine.connectWebSocket).toHaveBeenCalled();});
