-- 001_initial — the folder-sync journal, SPEC-ENGINE §4 (frozen at G1, sha256 c886f325ddd94668).
--
-- Copied from the spec's DDL block. Do not edit this file to change the schema:
-- migrations are forward-only (§4.2), so a schema change is a NEW numbered file.
--
-- PRAGMAs (journal_mode=WAL, synchronous=FULL, foreign_keys=ON, busy_timeout=5000,
-- wal_autocheckpoint=512) are applied by `Journal::open`, not here, because several of
-- them are connection-scoped and one (journal_mode) cannot run inside a transaction.

CREATE TABLE schema_version (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);

CREATE TABLE device (id TEXT PRIMARY KEY CHECK(id='singleton'),
  app_instance_id TEXT NOT NULL,            -- public.app_instances.id (uuid) — C13
  user_id TEXT, world TEXT NOT NULL, registered_at TEXT, last_heartbeat_at TEXT);

CREATE TABLE device_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, source TEXT NOT NULL, updated_at TEXT);
CREATE TABLE device_state (key TEXT PRIMARY KEY, value TEXT NOT NULL, detail TEXT, remedy TEXT, updated_at TEXT);

-- C10 — COPIED VERBATIM FROM SPEC-CUSTODY §8a @ 7ef61d4d. That spec is the source of these
-- columns; there is no local variant. Do not rename, reorder, add or drop a column here —
-- amend SPEC-CUSTODY §8a and re-paste.
CREATE TABLE session_state (
  id                        INTEGER PRIMARY KEY CHECK (id = 1),  -- exactly one row per journal
  state                     TEXT    NOT NULL,   -- honest-state enum (C3): signed_in | sign_in_needed |
                                                -- signed_out | credential_store_unavailable | offline
  state_reason              TEXT,               -- the remedy sentence every surface shows verbatim
  since                     TEXT    NOT NULL,   -- RFC3339; when this state was entered
  user_id                   TEXT,               -- Supabase user id (uuid) = the keychain account
  email                     TEXT,               -- for "Sign back in as …"; never part of an item name
  world                     TEXT    NOT NULL,   -- 'live' | 'dev'
  access_token_expires_at   TEXT,               -- RFC3339; scheduling uses monotonic time (S10), not this
  last_refresh_at           TEXT,
  last_attempt_at           TEXT,
  next_attempt_at           TEXT,               -- what the `offline` state shows the user
  failure_count             INTEGER NOT NULL DEFAULT 0,
  cloud_state_write_pending INTEGER NOT NULL DEFAULT 0,  -- S16 branch B: the write could not be made
  cloud_state_written_at    TEXT,
  notified_state            TEXT,               -- S18 dedup key: (notified_state, notified_since)
  notified_since            TEXT,
  updated_at                TEXT    NOT NULL
);

CREATE TABLE mappings (id TEXT PRIMARY KEY,        -- = files.sync_mappings.id
  organization_id TEXT NOT NULL,                   -- explicit, always (D12)
  cloud_kind TEXT NOT NULL CHECK(cloud_kind IN ('org_root','folder')), cloud_folder_id TEXT,
  local_root TEXT NOT NULL, local_root_volume_id TEXT NOT NULL,
  direction TEXT NOT NULL CHECK(direction IN ('two_way','upload_only','download_only')),
  desired_state TEXT NOT NULL DEFAULT 'active', state TEXT NOT NULL, state_detail TEXT,
  knobs TEXT NOT NULL DEFAULT '{}',                -- knowledge.index_for_knowledge lives here (C11)
  file_cursor TEXT, folder_cursor TEXT, cloud_row_version INTEGER,
  marker_uuid TEXT NOT NULL,                       -- .matrx-sync/marker contents (D8)
  created_at TEXT, updated_at TEXT, last_sync_at TEXT, last_full_rescan_at TEXT);

-- THE THREE TREES. One row per path per mapping; uniform key shape so the planner sees uniform rows.
CREATE TABLE tree_local (mapping_id TEXT NOT NULL, path_nfc TEXT NOT NULL, is_dir INTEGER NOT NULL,
  size INTEGER, mtime_ns INTEGER, volume_id TEXT, file_id TEXT,  -- inode (unix) / NTFS FileId, as text
  content_hash TEXT,                               -- SHA-256 hex; NULL only while unhashed (see I9)
  scanned_at TEXT, PRIMARY KEY(mapping_id, path_nfc)) WITHOUT ROWID;
CREATE TABLE tree_remote (mapping_id TEXT NOT NULL, path_nfc TEXT NOT NULL, is_dir INTEGER NOT NULL,
  size INTEGER, remote_file_id TEXT, remote_folder_id TEXT, remote_version INTEGER,
  checksum TEXT,                                   -- server SHA-256 (SPEC-SERVER)
  client_modified_at TEXT, origin_device_id TEXT, deleted_at TEXT, seen_at TEXT,
  PRIMARY KEY(mapping_id, path_nfc)) WITHOUT ROWID;
CREATE TABLE tree_synced (mapping_id TEXT NOT NULL, path_nfc TEXT NOT NULL, is_dir INTEGER NOT NULL,
  size INTEGER, mtime_ns INTEGER, volume_id TEXT, file_id TEXT,
  content_hash TEXT, remote_file_id TEXT NOT NULL, remote_version INTEGER NOT NULL, checksum TEXT,
  local_edit_flagged INTEGER NOT NULL DEFAULT 0,   -- download_only: a preserved local edit (D6)
  synced_at TEXT NOT NULL, PRIMARY KEY(mapping_id, path_nfc),
  CHECK (is_dir = 1 OR (content_hash IS NOT NULL AND checksum IS NOT NULL))) WITHOUT ROWID;
CREATE INDEX ix_local_identity  ON tree_local (mapping_id, volume_id, file_id);  -- rename: identity first
CREATE INDEX ix_local_hash      ON tree_local (mapping_id, content_hash);        -- rename: hash second
CREATE INDEX ix_synced_identity ON tree_synced(mapping_id, volume_id, file_id);
CREATE INDEX ix_remote_fileid   ON tree_remote(mapping_id, remote_file_id);

CREATE TABLE ops (id INTEGER PRIMARY KEY, mapping_id TEXT NOT NULL, seq INTEGER NOT NULL,
  kind TEXT NOT NULL, path_nfc TEXT NOT NULL, target_path_nfc TEXT,
  remote_file_id TEXT, expected_checksum TEXT, expected_version INTEGER, expected_local_hash TEXT,
  state TEXT NOT NULL CHECK(state IN ('ready','leased','blocked','failed','done')),
  attempts INTEGER NOT NULL DEFAULT 0, next_attempt_at TEXT,
  lease_owner TEXT, lease_expires_at TEXT, idempotency_key TEXT NOT NULL UNIQUE,
  transfer_offset INTEGER, transfer_upload_url TEXT,
  error_code TEXT, error_detail TEXT, created_at TEXT, updated_at TEXT);
CREATE INDEX ix_ops_queue ON ops(mapping_id, state, next_attempt_at, seq);   -- THE per-mapping queue

CREATE TABLE conflicts (id TEXT PRIMARY KEY, mapping_id TEXT NOT NULL, path_nfc TEXT NOT NULL,
  kind TEXT NOT NULL, local_hash TEXT, remote_file_id TEXT, remote_checksum TEXT,
  conflict_copy_path TEXT, detected_at TEXT NOT NULL, resolved_at TEXT, resolution TEXT);
CREATE TABLE activity (id INTEGER PRIMARY KEY, mapping_id TEXT, at TEXT NOT NULL, level TEXT NOT NULL,
  code TEXT NOT NULL, path_nfc TEXT, message TEXT, bytes INTEGER);
CREATE TABLE admission (mapping_id TEXT PRIMARY KEY, checked_at TEXT, verdict TEXT, flags TEXT);
CREATE TABLE ignore_cache (mapping_id TEXT PRIMARY KEY, rules_hash TEXT, compiled BLOB);
