import { useCallback, useEffect, useMemo, useState } from "react";
import { RefreshCw } from "lucide-react";
import { Badge, Button, BasicInput as Input } from "@ai-matrx/design-system";
import { PageHeader } from "@/components/layout/PageHeader";
import { engine, type CodexUsageMetric, type CodexUsageSnapshot } from "@/lib/api";

type Preset = "today" | "yesterday" | "last12h" | "custom";
type Grouping = "model" | "model_effort";
const fmt = (value: number) => new Intl.NumberFormat().format(value);
function rangeFor(preset: Preset, start: string, end: string) {
  const now = new Date(); if (preset === "last12h") return { start: new Date(now.getTime() - 43_200_000).toISOString(), end: now.toISOString() };
  if (preset === "custom") return { start: new Date(`${start}T00:00:00`).toISOString(), end: new Date(`${end}T00:00:00`).toISOString() };
  const day = new Date(now); day.setHours(0, 0, 0, 0); if (preset === "yesterday") { const until = day.toISOString(); day.setDate(day.getDate() - 1); return { start: day.toISOString(), end: until }; }
  return { start: day.toISOString(), end: now.toISOString() };
}
function Table({ title, rows, total }: { title: string; rows: CodexUsageMetric[]; total: number }) {
  return <section className="overflow-hidden rounded-lg border bg-card"><div className="border-b px-4 py-3 text-sm font-medium">{title}</div><div className="max-h-64 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted text-xs text-muted-foreground"><tr><th className="px-4 py-2 text-left">Name</th><th className="px-4 py-2 text-right">Tokens</th><th className="px-4 py-2 text-right">Share</th><th className="px-4 py-2 text-right">Responses</th><th className="px-4 py-2 text-right">Credits</th></tr></thead><tbody>{rows.map((row, index) => <tr className="border-t" key={`${row.conversation_id ?? row.project ?? row.model}-${row.effort ?? ""}-${index}`}><td className="max-w-[22rem] truncate px-4 py-2">{row.conversation_title ?? row.project ?? row.model}{row.effort ? ` · ${row.effort}` : ""}<span className="ml-2 text-xs text-muted-foreground">{row.conversation_title ? row.model : ""}</span></td><td className="px-4 py-2 text-right tabular-nums">{fmt(row.total_tokens)}</td><td className="px-4 py-2 text-right tabular-nums">{total ? `${(row.total_tokens * 100 / total).toFixed(1)}%` : "0%"}</td><td className="px-4 py-2 text-right tabular-nums">{fmt(row.response_count)}</td><td className="px-4 py-2 text-right tabular-nums">{row.estimated_standard_credits == null ? "—" : row.estimated_standard_credits.toFixed(2)}</td></tr>)}</tbody></table>{rows.length === 0 && <p className="p-6 text-sm text-muted-foreground">No recorded usage in this range.</p>}</div></section>;
}
export function CodexUsage() {
  const [preset, setPreset] = useState<Preset>("today"), [grouping, setGrouping] = useState<Grouping>("model"), [start, setStart] = useState(() => new Date().toISOString().slice(0, 10)), [end, setEnd] = useState(() => new Date().toISOString().slice(0, 10)), [snapshot, setSnapshot] = useState<CodexUsageSnapshot | null>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(false);
  const range = useMemo(() => rangeFor(preset, start, end), [preset, start, end]);
  const load = useCallback(async (refresh = false) => { setLoading(true); setError(null); try { setSnapshot(await engine.getCodexUsage({ ...range, grouping, refresh })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to read Codex usage."); } finally { setLoading(false); } }, [range, grouping]);
  useEffect(() => { void load(); }, [load]);
  const total = snapshot?.totals.total_tokens ?? 0, models = grouping === "model" ? snapshot?.models ?? [] : snapshot?.model_effort ?? [];
  return <div className="flex h-full flex-col overflow-hidden"><PageHeader title="Codex Usage" description="Sanitized local activity from this Mac. No conversation content leaves the engine."><Button size="sm" disabled={loading} onClick={() => void load(true)}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</Button></PageHeader><div className="flex-1 space-y-5 overflow-auto p-5"><div className="flex flex-wrap gap-2"><div className="flex rounded-md border p-0.5">{(["today", "yesterday", "last12h", "custom"] as Preset[]).map(item => <Button key={item} size="sm" variant={preset === item ? "default" : "ghost"} onClick={() => setPreset(item)}>{{ today: "Today", yesterday: "Yesterday", last12h: "Last 12h", custom: "Custom" }[item]}</Button>)}</div><div className="flex rounded-md border p-0.5"><Button size="sm" variant={grouping === "model" ? "default" : "ghost"} onClick={() => setGrouping("model")}>Model</Button><Button size="sm" variant={grouping === "model_effort" ? "default" : "ghost"} onClick={() => setGrouping("model_effort")}>Model + effort</Button></div>{preset === "custom" && <><Input type="date" aria-label="Start date" value={start} onChange={event => setStart(event.target.value)} /><Input type="date" aria-label="End date" value={end} onChange={event => setEnd(event.target.value)} /></>}</div>{error && <p className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{snapshot && <><div className="grid gap-3 md:grid-cols-4"><Card label="Total tokens" value={fmt(total)} sub={`${fmt(snapshot.totals.response_count)} responses`} /><Card label="Estimated standard credits" value={(snapshot.credits.estimated_standard ?? 0).toFixed(2)} sub="Not actual Pro allowance debits" /><Card label="Measured allowance" value="Unavailable" sub="No local allowance ledger is exposed" /><Card label="Collected" value={new Date(snapshot.collected_at).toLocaleString()} sub={`${snapshot.coverage.scanned_files}/${snapshot.coverage.indexed_files} indexed files`} badge={snapshot.coverage.complete ? "Complete coverage" : "Partial coverage"} /></div><p className="text-xs text-muted-foreground">{snapshot.coverage.notes.join(" ")}</p><Table title={grouping === "model" ? "Models" : "Models and effort"} rows={models} total={total} /><div className="grid gap-5 lg:grid-cols-2"><Table title="Projects" rows={snapshot.projects} total={total} /><Table title="Conversations" rows={snapshot.conversations} total={total} /></div><Table title="Parent-worker drilldown" rows={snapshot.workers} total={total} /><div className="rounded-lg border bg-muted/30 p-4 text-xs text-muted-foreground">{snapshot.qualification.map(item => <p className="mb-1" key={item}>{item}</p>)}</div></>}</div></div>;
}
function Card({ label, value, sub, badge }: { label: string; value: string; sub: string; badge?: string }) { return <div className="rounded-lg border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 truncate text-xl font-semibold tabular-nums">{value}</p><p className="text-xs text-muted-foreground">{sub}</p>{badge && <Badge className="mt-2" variant={badge.startsWith("Complete") ? "default" : "secondary"}>{badge}</Badge>}</div>; }
