"""Vendored compiled-fallback catalog data for kinds whose source of truth
lives OUTSIDE Python (Rust consts / desktop TS constants).

GENERATED — do not hand-edit. Regenerate with

    uv run python scripts/generate_catalog_fallback.py

whenever the Rust/TS fallback constants change; the drift guard
(tests/unit/test_catalog_fallback_drift.py) re-extracts from the sources at
test time and fails the suite until this file is regenerated. Python-sourced
kinds (image/video/TTS/NER/wake-word/LoRA/presets) are NOT vendored here —
compiled.py adapts them live from their legacy in-code lists so they can
never drift.

Shape per kind: list of dicts matching the ``catalog_entries`` seed shape
(key / payload / artifact_* / sort_order / notes?).
"""

from __future__ import annotations

from typing import Any

# Source: desktop/src-tauri/src/llm/model_selector.rs
COMPILED_LLM_MODEL_ENTRIES: list[dict[str, Any]] = [{'key': 'LowAlt',
  'payload': {'tier': 'LowAlt',
              'name': 'Phi 4 Mini',
              'provider': 'Microsoft',
              'filename': 'microsoft_Phi-4-mini-instruct-Q4_K_M.gguf',
              'disk_size_gb': 2.5,
              'ram_required_gb': 3.5,
              'text_rating': 2,
              'code_rating': 2,
              'vision_rating': 0,
              'tool_calling_rating': 3,
              'speed': 'Very fast',
              'description': "Microsoft's smallest model. Fastest option for very low-RAM "
                             'machines.',
              'knowledge_cutoff': 'Mar 2025',
              'hf_model_card_url': 'https://huggingface.co/microsoft/Phi-4-mini-instruct',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF/resolve/main/microsoft_Phi-4-mini-instruct-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 8192,
              'expected_size_bytes': 2491874688,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF/resolve/main/microsoft_Phi-4-mini-instruct-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 2491874688,
  'sort_order': 0},
 {'key': 'Phi4MiniReasoning',
  'payload': {'tier': 'Phi4MiniReasoning',
              'name': 'Phi 4 Mini Reasoning',
              'provider': 'Microsoft',
              'filename': 'Phi-4-mini-reasoning-Q4_K_M.gguf',
              'disk_size_gb': 2.5,
              'ram_required_gb': 3.5,
              'text_rating': 2,
              'code_rating': 3,
              'vision_rating': 0,
              'tool_calling_rating': 2,
              'speed': 'Very fast',
              'description': 'Tiny STEM/math reasoner. Same footprint as Phi 4 Mini but tuned for '
                             'step-by-step reasoning.',
              'knowledge_cutoff': 'Apr 2025',
              'hf_model_card_url': 'https://huggingface.co/microsoft/Phi-4-mini-reasoning',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/Phi-4-mini-reasoning-GGUF/resolve/main/Phi-4-mini-reasoning-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 32768,
              'expected_size_bytes': 2491875232,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Phi-4-mini-reasoning-GGUF/resolve/main/Phi-4-mini-reasoning-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 2491875232,
  'sort_order': 10},
 {'key': 'Qwen35_2B',
  'payload': {'tier': 'Qwen35_2B',
              'name': 'Qwen 3.5 2B',
              'provider': 'Alibaba',
              'filename': 'Qwen3.5-2B-Q4_K_M.gguf',
              'disk_size_gb': 1.3,
              'ram_required_gb': 3.0,
              'text_rating': 2,
              'code_rating': 2,
              'vision_rating': 3,
              'tool_calling_rating': 3,
              'speed': 'Very fast',
              'description': 'Smallest Qwen 3.5 with native vision. Ideal for phones, old laptops, '
                             'and ultra-low RAM machines.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3.5-2B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/Qwen3.5-2B-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 1280835840,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-Qwen3.5-2B-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 668227264,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/Qwen3.5-2B-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 1280835840,
  'sort_order': 20},
 {'key': 'Low',
  'payload': {'tier': 'Low',
              'name': 'Qwen 3 4B',
              'provider': 'Alibaba',
              'filename': 'Qwen3-4B-Q4_K_M.gguf',
              'disk_size_gb': 2.5,
              'ram_required_gb': 4.0,
              'text_rating': 2,
              'code_rating': 2,
              'vision_rating': 0,
              'tool_calling_rating': 3,
              'speed': 'Fast',
              'description': 'Compact model with strong tool calling. Prefer Qwen 3.5 4B when '
                             'available.',
              'knowledge_cutoff': 'Sep 2024',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3-4B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/Qwen/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 8192,
              'expected_size_bytes': 2497280256,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/Qwen/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 2497280256,
  'sort_order': 30},
 {'key': 'Qwen35_4B',
  'payload': {'tier': 'Qwen35_4B',
              'name': 'Qwen 3.5 4B',
              'provider': 'Alibaba',
              'filename': 'Qwen3.5-4B-Q4_K_M.gguf',
              'disk_size_gb': 2.7,
              'ram_required_gb': 4.5,
              'text_rating': 3,
              'code_rating': 3,
              'vision_rating': 3,
              'tool_calling_rating': 4,
              'speed': 'Fast',
              'description': 'Best tiny multimodal model. Strong tools + vision in ~2.7 GB — '
                             'preferred over Qwen 3 4B.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3.5-4B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/Qwen3.5-4B-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 2740937888,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-Qwen3.5-4B-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 672423616,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/Qwen3.5-4B-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 2740937888,
  'sort_order': 40},
 {'key': 'Gemma3nE2B',
  'payload': {'tier': 'Gemma3nE2B',
              'name': 'Gemma 3n E2B',
              'provider': 'Google',
              'filename': 'gemma-3n-E2B-it-Q4_K_M.gguf',
              'disk_size_gb': 2.82,
              'ram_required_gb': 4.0,
              'text_rating': 2,
              'code_rating': 1,
              'vision_rating': 0,
              'tool_calling_rating': 2,
              'speed': 'Very fast',
              'description': "Google's smallest on-device Gemma 3n. Text-only via llama.cpp "
                             'currently. Completes the 3n edge pair with E4B.',
              'knowledge_cutoff': 'Mar 2025',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-3n-E2B-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/gemma-3n-E2B-it-GGUF/resolve/main/gemma-3n-E2B-it-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 32768,
              'expected_size_bytes': 3026881888,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/gemma-3n-E2B-it-GGUF/resolve/main/gemma-3n-E2B-it-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 3026881888,
  'sort_order': 50},
 {'key': 'Gemma4E2B',
  'payload': {'tier': 'Gemma4E2B',
              'name': 'Gemma 4 E2B',
              'provider': 'Google',
              'filename': 'gemma-4-E2B-it-Q4_K_M.gguf',
              'disk_size_gb': 3.1,
              'ram_required_gb': 5.5,
              'text_rating': 2,
              'code_rating': 2,
              'vision_rating': 3,
              'tool_calling_rating': 2,
              'speed': 'Fast',
              'description': "Google's smallest Gemma 4. Multimodal: text + image input via "
                             'llama.cpp (audio support pending upstream). 2B effective params with '
                             'PLE. Ideal for edge devices.',
              'knowledge_cutoff': 'Apr 2026',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-4-E2B-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 3106736256,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-gemma-4-E2B-it-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 985654080,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'Q4_K_M',
                            'filename': 'gemma-4-E2B-it-Q4_K_M.gguf',
                            'disk_size_gb': 3.1,
                            'ram_required_gb': 5.5,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q4_K_M.gguf',
                            'expected_size_bytes': 3106736256,
                            'mmproj_filename': 'mmproj-gemma-4-E2B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 985654080},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Quality',
                            'quant': 'Q8_0',
                            'filename': 'gemma-4-E2B-it-Q8_0.gguf',
                            'disk_size_gb': 5.0,
                            'ram_required_gb': 7.5,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q8_0.gguf',
                            'expected_size_bytes': 5048350848,
                            'mmproj_filename': 'mmproj-gemma-4-E2B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 985654080}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 60,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'UltraLow',
  'payload': {'tier': 'UltraLow',
              'name': 'Gemma 3n E4B',
              'provider': 'Google',
              'filename': 'gemma-3n-E4B-it-Q4_K_M.gguf',
              'disk_size_gb': 4.54,
              'ram_required_gb': 6.0,
              'text_rating': 2,
              'code_rating': 1,
              'vision_rating': 0,
              'tool_calling_rating': 2,
              'speed': 'Fast',
              'description': "Google's ultra-efficient on-device model. Designed for phones and "
                             'edge devices. Text-only via llama.cpp currently.',
              'knowledge_cutoff': 'Mar 2025',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-3n-E4B-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/gemma-3n-E4B-it-GGUF/resolve/main/gemma-3n-E4B-it-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 32768,
              'expected_size_bytes': 4876000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/gemma-3n-E4B-it-GGUF/resolve/main/gemma-3n-E4B-it-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 4876000000,
  'sort_order': 70},
 {'key': 'Gemma4E4B',
  'payload': {'tier': 'Gemma4E4B',
              'name': 'Gemma 4 E4B',
              'provider': 'Google',
              'filename': 'gemma-4-E4B-it-Q4_K_M.gguf',
              'disk_size_gb': 5.0,
              'ram_required_gb': 7.5,
              'text_rating': 3,
              'code_rating': 2,
              'vision_rating': 4,
              'tool_calling_rating': 2,
              'speed': 'Fast',
              'description': 'Gemma 4 multimodal: text + image input via llama.cpp (audio support '
                             'pending upstream). 4B effective params. Excellent vision quality for '
                             'its size. 128K context.',
              'knowledge_cutoff': 'Apr 2026',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-4-E4B-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 4977169568,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-gemma-4-E4B-it-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 990372672,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'Q4_K_M',
                            'filename': 'gemma-4-E4B-it-Q4_K_M.gguf',
                            'disk_size_gb': 5.0,
                            'ram_required_gb': 7.5,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q4_K_M.gguf',
                            'expected_size_bytes': 4977169568,
                            'mmproj_filename': 'mmproj-gemma-4-E4B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 990372672},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Quality',
                            'quant': 'Q8_0',
                            'filename': 'gemma-4-E4B-it-Q8_0.gguf',
                            'disk_size_gb': 8.2,
                            'ram_required_gb': 10.5,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q8_0.gguf',
                            'expected_size_bytes': 8192951456,
                            'mmproj_filename': 'mmproj-gemma-4-E4B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 990372672}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 80,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'Low2',
  'payload': {'tier': 'Low2',
              'name': 'DeepSeek R1 0528 Qwen3 8B',
              'provider': 'DeepSeek',
              'filename': 'DeepSeek-R1-0528-Qwen3-8B-Q4_K_M.gguf',
              'disk_size_gb': 5.0,
              'ram_required_gb': 6.5,
              'text_rating': 3,
              'code_rating': 4,
              'vision_rating': 0,
              'tool_calling_rating': 3,
              'speed': 'Fast',
              'description': 'Latest R1 distill on Qwen3-8B (May 2025). Stronger reasoning than '
                             'the older Llama-8B distill at the same size.',
              'knowledge_cutoff': 'May 2025',
              'hf_model_card_url': 'https://huggingface.co/deepseek-ai/DeepSeek-R1-0528-Qwen3-8B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/DeepSeek-R1-0528-Qwen3-8B-GGUF/resolve/main/DeepSeek-R1-0528-Qwen3-8B-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 5027785216,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/DeepSeek-R1-0528-Qwen3-8B-GGUF/resolve/main/DeepSeek-R1-0528-Qwen3-8B-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 5027785216,
  'sort_order': 90},
 {'key': 'Low3',
  'payload': {'tier': 'Low3',
              'name': 'Llama 3.1 8B',
              'provider': 'Meta',
              'filename': 'Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
              'disk_size_gb': 4.92,
              'ram_required_gb': 6.0,
              'text_rating': 2,
              'code_rating': 2,
              'vision_rating': 0,
              'tool_calling_rating': 3,
              'speed': 'Fast',
              'description': "Meta's reliable 8B workhorse with 128k context. Wide ecosystem "
                             'support, excellent tool calling.',
              'knowledge_cutoff': 'Mar 2023',
              'hf_model_card_url': 'https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 5284000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 5284000000,
  'sort_order': 100},
 {'key': 'Default',
  'payload': {'tier': 'Default',
              'name': 'Qwen 3 8B',
              'provider': 'Alibaba',
              'filename': 'Qwen3-8B-Q4_K_M.gguf',
              'disk_size_gb': 5.1,
              'ram_required_gb': 6.5,
              'text_rating': 3,
              'code_rating': 3,
              'vision_rating': 0,
              'tool_calling_rating': 4,
              'speed': 'Medium',
              'description': 'Solid mid-size generalist. Prefer Qwen 3.5 9B when available (vision '
                             '+ newer quality).',
              'knowledge_cutoff': 'Sep 2024',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3-8B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/Qwen/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 8192,
              'expected_size_bytes': 5027783488,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/Qwen/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 5027783488,
  'sort_order': 110},
 {'key': 'Qwen35_9B',
  'payload': {'tier': 'Qwen35_9B',
              'name': 'Qwen 3.5 9B',
              'provider': 'Alibaba',
              'filename': 'Qwen3.5-9B-Q4_K_M.gguf',
              'disk_size_gb': 5.7,
              'ram_required_gb': 8.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 4,
              'tool_calling_rating': 4,
              'speed': 'Medium',
              'description': 'Recommended default. Dense 9B with native vision, strong tools, and '
                             '262K context — best everyday local model.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3.5-9B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-9B-GGUF/resolve/main/Qwen3.5-9B-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 5680522464,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-Qwen3.5-9B-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-9B-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 918166080,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Qwen3.5-9B-GGUF/resolve/main/Qwen3.5-9B-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 5680522464,
  'sort_order': 120},
 {'key': 'GlmZ1_9B',
  'payload': {'tier': 'GlmZ1_9B',
              'name': 'GLM Z1 9B',
              'provider': 'Z.ai',
              'filename': 'GLM-Z1-9B-0414-Q4_K_M.gguf',
              'disk_size_gb': 6.2,
              'ram_required_gb': 8.0,
              'text_rating': 3,
              'code_rating': 4,
              'vision_rating': 0,
              'tool_calling_rating': 4,
              'speed': 'Medium',
              'description': 'Compact GLM reasoner. Fits 8 GB machines — the small sibling to GLM '
                             '4.7 Flash for mid-RAM agent/reasoning workloads.',
              'knowledge_cutoff': 'Apr 2025',
              'hf_model_card_url': 'https://huggingface.co/THUDM/GLM-Z1-9B-0414',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/GLM-Z1-9B-0414-GGUF/resolve/main/GLM-Z1-9B-0414-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 32768,
              'expected_size_bytes': 6166575232,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/GLM-Z1-9B-0414-GGUF/resolve/main/GLM-Z1-9B-0414-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 6166575232,
  'sort_order': 130},
 {'key': 'Mid',
  'payload': {'tier': 'Mid',
              'name': 'Gemma 3 12B',
              'provider': 'Google',
              'filename': 'google_gemma-3-12b-it-qat-Q4_K_M.gguf',
              'disk_size_gb': 7.3,
              'ram_required_gb': 10.0,
              'text_rating': 3,
              'code_rating': 3,
              'vision_rating': 3,
              'tool_calling_rating': 3,
              'speed': 'Medium',
              'description': "Google's mid-size multimodal model with QAT quantization. Prefer "
                             'Gemma 4 12B for newer quality and Apache-2.0.',
              'knowledge_cutoff': 'Mar 2025',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-3-12b-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/bartowski/google_gemma-3-12b-it-qat-GGUF/resolve/main/google_gemma-3-12b-it-qat-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 7840000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/google_gemma-3-12b-it-qat-GGUF/resolve/main/google_gemma-3-12b-it-qat-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 7840000000,
  'sort_order': 140},
 {'key': 'Gemma4_12B',
  'payload': {'tier': 'Gemma4_12B',
              'name': 'Gemma 4 12B',
              'provider': 'Google',
              'filename': 'gemma-4-12b-it-Q4_K_M.gguf',
              'disk_size_gb': 7.1,
              'ram_required_gb': 9.0,
              'text_rating': 4,
              'code_rating': 3,
              'vision_rating': 4,
              'tool_calling_rating': 3,
              'speed': 'Medium',
              'description': 'Gemma 4 Unified 12B — the missing mid-size. Text + image, 256K '
                             'context, compact mmproj (~167 MB). Best Gemma for 8–16 GB machines.',
              'knowledge_cutoff': 'Jun 2026',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-4-12B-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/gemma-4-12B-it-GGUF/resolve/main/gemma-4-12b-it-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 7121860000,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-gemma-4-12B-it-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-12B-it-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 175115840,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'Q4_K_M',
                            'filename': 'gemma-4-12b-it-Q4_K_M.gguf',
                            'disk_size_gb': 7.1,
                            'ram_required_gb': 9.0,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-12B-it-GGUF/resolve/main/gemma-4-12b-it-Q4_K_M.gguf',
                            'expected_size_bytes': 7121860000,
                            'mmproj_filename': 'mmproj-gemma-4-12B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-12B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 175115840},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Quality',
                            'quant': 'Q8_0',
                            'filename': 'gemma-4-12b-it-Q8_0.gguf',
                            'disk_size_gb': 12.7,
                            'ram_required_gb': 15.0,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-12B-it-GGUF/resolve/main/gemma-4-12b-it-Q8_0.gguf',
                            'expected_size_bytes': 12669646240,
                            'mmproj_filename': 'mmproj-gemma-4-12B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-12B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 175115840}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 150,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'Mid2',
  'payload': {'tier': 'Mid2',
              'name': 'Phi 4 Reasoning Plus',
              'provider': 'Microsoft',
              'filename': 'Phi-4-reasoning-plus-Q4_K_M.gguf',
              'disk_size_gb': 9.1,
              'ram_required_gb': 12.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 0,
              'tool_calling_rating': 3,
              'speed': 'Medium',
              'description': "Microsoft's upgraded 14B reasoner. Stronger STEM/code than the "
                             'original Phi-4-reasoning at the same size class.',
              'knowledge_cutoff': 'Apr 2025',
              'hf_model_card_url': 'https://huggingface.co/microsoft/Phi-4-reasoning-plus',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/Phi-4-reasoning-plus-GGUF/resolve/main/Phi-4-reasoning-plus-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 32768,
              'expected_size_bytes': 9053117120,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Phi-4-reasoning-plus-GGUF/resolve/main/Phi-4-reasoning-plus-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 9053117120,
  'sort_order': 160},
 {'key': 'High',
  'payload': {'tier': 'High',
              'name': 'GPT OSS 20B',
              'provider': 'OpenAI',
              'filename': 'openai_gpt-oss-20b-MXFP4.gguf',
              'disk_size_gb': 12.1,
              'ram_required_gb': 16.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 0,
              'tool_calling_rating': 4,
              'speed': 'Medium',
              'description': "OpenAI's open-source reasoning model — equivalent to o3-mini. Only "
                             '3.6B active params (MoE). Apache 2.0.',
              'knowledge_cutoff': 'Mid 2025',
              'hf_model_card_url': 'https://huggingface.co/openai/gpt-oss-20b',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/bartowski/openai_gpt-oss-20b-GGUF/resolve/main/openai_gpt-oss-20b-MXFP4.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 12991000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/openai_gpt-oss-20b-GGUF/resolve/main/openai_gpt-oss-20b-MXFP4.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 12991000000,
  'sort_order': 170},
 {'key': 'HighAlt',
  'payload': {'tier': 'HighAlt',
              'name': 'Mistral Small 3.1 24B',
              'provider': 'Mistral',
              'filename': 'Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf',
              'disk_size_gb': 14.4,
              'ram_required_gb': 16.0,
              'text_rating': 3,
              'code_rating': 3,
              'vision_rating': 2,
              'tool_calling_rating': 4,
              'speed': 'GPU recommended',
              'description': "Mistral's dense 24B with strong tool calling and 128k context. "
                             'Excellent for agents.',
              'knowledge_cutoff': 'Mar 2025',
              'hf_model_card_url': 'https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/lmstudio-community/Mistral-Small-3.1-24B-Instruct-2503-GGUF/resolve/main/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 4096,
              'expected_size_bytes': 14333910176,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/lmstudio-community/Mistral-Small-3.1-24B-Instruct-2503-GGUF/resolve/main/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 14333910176,
  'sort_order': 180},
 {'key': 'Devstral24B',
  'payload': {'tier': 'Devstral24B',
              'name': 'Devstral Small 2 24B',
              'provider': 'Mistral',
              'filename': 'mistralai_Devstral-Small-2-24B-Instruct-2512-Q4_K_M.gguf',
              'disk_size_gb': 14.3,
              'ram_required_gb': 16.0,
              'text_rating': 3,
              'code_rating': 5,
              'vision_rating': 0,
              'tool_calling_rating': 4,
              'speed': 'GPU recommended',
              'description': "Mistral's agentic coding specialist. Dense 24B tuned for software "
                             'engineering and tool use.',
              'knowledge_cutoff': 'Nov 2025',
              'hf_model_card_url': 'https://huggingface.co/mistralai/Devstral-Small-2-24B-Instruct-2512',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/bartowski/mistralai_Devstral-Small-2-24B-Instruct-2512-GGUF/resolve/main/mistralai_Devstral-Small-2-24B-Instruct-2512-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 14334438272,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/mistralai_Devstral-Small-2-24B-Instruct-2512-GGUF/resolve/main/mistralai_Devstral-Small-2-24B-Instruct-2512-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 14334438272,
  'sort_order': 190},
 {'key': 'Coder30B',
  'payload': {'tier': 'Coder30B',
              'name': 'Qwen 3 Coder 30B A3B',
              'provider': 'Alibaba',
              'filename': 'Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf',
              'disk_size_gb': 18.6,
              'ram_required_gb': 22.0,
              'text_rating': 3,
              'code_rating': 5,
              'vision_rating': 0,
              'tool_calling_rating': 5,
              'speed': 'GPU recommended',
              'description': 'Coding MoE: 30B total / 3B active. Best agentic coding model in the '
                             '16–24 GB band. 256K context.',
              'knowledge_cutoff': 'Jul 2025',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF/resolve/main/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 18556689568,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF/resolve/main/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 18556689568,
  'sort_order': 200},
 {'key': 'Glm47Flash',
  'payload': {'tier': 'Glm47Flash',
              'name': 'GLM 4.7 Flash',
              'provider': 'Z.ai',
              'filename': 'GLM-4.7-Flash-Q4_K_M.gguf',
              'disk_size_gb': 18.3,
              'ram_required_gb': 22.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 0,
              'tool_calling_rating': 5,
              'speed': 'GPU recommended',
              'description': 'Z.ai agent MoE (~30B / ~3B active). Strong tool calling and '
                             'SWE-style agent workloads — non-Qwen alternative to 35B-A3B.',
              'knowledge_cutoff': 'Jan 2026',
              'hf_model_card_url': 'https://huggingface.co/zai-org/GLM-4.7-Flash',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/GLM-4.7-Flash-GGUF/resolve/main/GLM-4.7-Flash-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 202752,
              'expected_size_bytes': 18312339808,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/GLM-4.7-Flash-GGUF/resolve/main/GLM-4.7-Flash-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 18312339808,
  'sort_order': 210},
 {'key': 'Gemma4A4B',
  'payload': {'tier': 'Gemma4A4B',
              'name': 'Gemma 4 26B A4B',
              'provider': 'Google',
              'filename': 'gemma-4-26B-A4B-it-UD-Q4_K_M.gguf',
              'disk_size_gb': 17.0,
              'ram_required_gb': 20.0,
              'text_rating': 4,
              'code_rating': 3,
              'vision_rating': 4,
              'tool_calling_rating': 3,
              'speed': 'GPU recommended',
              'description': 'Gemma 4 MoE: 26B total / 4B active. Near-31B quality at 4B speed. '
                             'Text + image multimodal. 256K context. Best value Gemma 4.',
              'knowledge_cutoff': 'Apr 2026',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-4-26B-A4B-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/gemma-4-26B-A4B-it-UD-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 16947539744,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-gemma-4-26B-A4B-it-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 1193058784,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'UD-Q4_K_M',
                            'filename': 'gemma-4-26B-A4B-it-UD-Q4_K_M.gguf',
                            'disk_size_gb': 17.0,
                            'ram_required_gb': 20.0,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/gemma-4-26B-A4B-it-UD-Q4_K_M.gguf',
                            'expected_size_bytes': 16947539744,
                            'mmproj_filename': 'mmproj-gemma-4-26B-A4B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 1193058784},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Quality',
                            'quant': 'Q8_0',
                            'filename': 'gemma-4-26B-A4B-it-Q8_0.gguf',
                            'disk_size_gb': 26.9,
                            'ram_required_gb': 30.0,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/gemma-4-26B-A4B-it-Q8_0.gguf',
                            'expected_size_bytes': 26859859744,
                            'mmproj_filename': 'mmproj-gemma-4-26B-A4B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 1193058784}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 220,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'High2',
  'payload': {'tier': 'High2',
              'name': 'Qwen 3.5 27B',
              'provider': 'Alibaba',
              'filename': 'Qwen3.5-27B-UD-IQ3_XXS.gguf',
              'disk_size_gb': 11.5,
              'ram_required_gb': 14.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 3,
              'tool_calling_rating': 4,
              'speed': 'GPU recommended',
              'description': 'Dense 27B with native vision. Arena rank #24 among all open-source '
                             'models. Choose your size below.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3.5-27B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-27B-GGUF/resolve/main/Qwen3.5-27B-UD-IQ3_XXS.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 12344000000,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-Qwen3.5-27B-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-27B-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 927607040,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'IQ3_XXS',
                            'filename': 'Qwen3.5-27B-UD-IQ3_XXS.gguf',
                            'disk_size_gb': 11.5,
                            'ram_required_gb': 14.0,
                            'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-27B-GGUF/resolve/main/Qwen3.5-27B-UD-IQ3_XXS.gguf',
                            'expected_size_bytes': 12344000000,
                            'mmproj_filename': 'mmproj-Qwen3.5-27B-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-27B-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 927607040},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Balanced',
                            'quant': 'Q4_K_M',
                            'filename': 'Qwen3.5-27B-Q4_K_M.gguf',
                            'disk_size_gb': 16.7,
                            'ram_required_gb': 20.0,
                            'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-27B-GGUF/resolve/main/Qwen3.5-27B-Q4_K_M.gguf',
                            'expected_size_bytes': 17933000000,
                            'mmproj_filename': 'mmproj-Qwen3.5-27B-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-27B-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 927607040}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 230,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'Gemma4_31B',
  'payload': {'tier': 'Gemma4_31B',
              'name': 'Gemma 4 31B',
              'provider': 'Google',
              'filename': 'gemma-4-31B-it-Q4_K_M.gguf',
              'disk_size_gb': 18.3,
              'ram_required_gb': 21.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 5,
              'tool_calling_rating': 3,
              'speed': 'GPU recommended',
              'description': "Google's flagship Gemma 4. Dense 31B with top-tier vision. Text + "
                             'image multimodal. 256K context. Built-in thinking mode.',
              'knowledge_cutoff': 'Apr 2026',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-4-31B-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/gemma-4-31B-it-GGUF/resolve/main/gemma-4-31B-it-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 18323731456,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-gemma-4-31B-it-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-31B-it-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 1198957024,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'Q4_K_M',
                            'filename': 'gemma-4-31B-it-Q4_K_M.gguf',
                            'disk_size_gb': 18.3,
                            'ram_required_gb': 21.0,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-31B-it-GGUF/resolve/main/gemma-4-31B-it-Q4_K_M.gguf',
                            'expected_size_bytes': 18323731456,
                            'mmproj_filename': 'mmproj-gemma-4-31B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-31B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 1198957024},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Quality',
                            'quant': 'Q8_0',
                            'filename': 'gemma-4-31B-it-Q8_0.gguf',
                            'disk_size_gb': 32.6,
                            'ram_required_gb': 36.0,
                            'hf_url': 'https://huggingface.co/unsloth/gemma-4-31B-it-GGUF/resolve/main/gemma-4-31B-it-Q8_0.gguf',
                            'expected_size_bytes': 32635675648,
                            'mmproj_filename': 'mmproj-gemma-4-31B-it-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/gemma-4-31B-it-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 1198957024}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 240,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'High3',
  'payload': {'tier': 'High3',
              'name': 'DeepSeek R1 Distill 32B',
              'provider': 'DeepSeek',
              'filename': 'DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
              'disk_size_gb': 19.85,
              'ram_required_gb': 24.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 0,
              'tool_calling_rating': 3,
              'speed': 'GPU recommended',
              'description': "DeepSeek's 32B reasoning distill. Exceptional chain-of-thought for "
                             'its size. Fits in 24 GB VRAM.',
              'knowledge_cutoff': 'Jul 2024',
              'hf_model_card_url': 'https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 21313000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 21313000000,
  'sort_order': 250},
 {'key': 'High4',
  'payload': {'tier': 'High4',
              'name': 'Gemma 3 27B',
              'provider': 'Google',
              'filename': 'google_gemma-3-27b-it-Q4_K_M.gguf',
              'disk_size_gb': 16.55,
              'ram_required_gb': 20.0,
              'text_rating': 4,
              'code_rating': 3,
              'vision_rating': 4,
              'tool_calling_rating': 3,
              'speed': 'GPU recommended',
              'description': "Google's best open multimodal model from the Gemma 3 line. Prefer "
                             'Gemma 4 26B A4B / 31B for newer quality.',
              'knowledge_cutoff': 'Mar 2025',
              'hf_model_card_url': 'https://huggingface.co/google/gemma-3-27b-it',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/gemma-3-27b-it-GGUF/resolve/main/gemma-3-27b-it-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 17773000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/gemma-3-27b-it-GGUF/resolve/main/gemma-3-27b-it-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 17773000000,
  'sort_order': 260},
 {'key': 'VHigh',
  'payload': {'tier': 'VHigh',
              'name': 'Qwen 3.5 35B A3B',
              'provider': 'Alibaba',
              'filename': 'Qwen3.5-35B-A3B-UD-IQ4_XS.gguf',
              'disk_size_gb': 17.5,
              'ram_required_gb': 22.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 4,
              'tool_calling_rating': 4,
              'speed': 'GPU recommended',
              'description': 'Top open-source MoE model. Only 3B active params — inference speed '
                             'of a 3B with quality far above. Arena rank #28. Choose your size '
                             'below.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3.5-35B-A3B',
              'is_uncensored': False,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/Qwen3.5-35B-A3B-UD-IQ4_XS.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 18790000000,
              'hf_part_sizes': [],
              'mmproj_filename': 'mmproj-Qwen3.5-35B-A3B-F16.gguf',
              'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/mmproj-F16.gguf',
              'mmproj_expected_size_bytes': 899283648,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'UD-IQ2_M',
                            'filename': 'Qwen3.5-35B-A3B-UD-IQ2_M.gguf',
                            'disk_size_gb': 11.4,
                            'ram_required_gb': 14.0,
                            'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/Qwen3.5-35B-A3B-UD-IQ2_M.gguf',
                            'expected_size_bytes': 12238000000,
                            'mmproj_filename': 'mmproj-Qwen3.5-35B-A3B-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 899283648},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Balanced',
                            'quant': 'UD-IQ4_XS',
                            'filename': 'Qwen3.5-35B-A3B-UD-IQ4_XS.gguf',
                            'disk_size_gb': 17.5,
                            'ram_required_gb': 22.0,
                            'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/Qwen3.5-35B-A3B-UD-IQ4_XS.gguf',
                            'expected_size_bytes': 18790000000,
                            'mmproj_filename': 'mmproj-Qwen3.5-35B-A3B-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 899283648},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Quality',
                            'quant': 'Q4_K_M',
                            'filename': 'Qwen3.5-35B-A3B-Q4_K_M.gguf',
                            'disk_size_gb': 22.0,
                            'ram_required_gb': 26.0,
                            'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/Qwen3.5-35B-A3B-Q4_K_M.gguf',
                            'expected_size_bytes': 23622000000,
                            'mmproj_filename': 'mmproj-Qwen3.5-35B-A3B-F16.gguf',
                            'mmproj_url': 'https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/mmproj-F16.gguf',
                            'mmproj_expected_size_bytes': 899283648}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 270,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'UncensoredCompact',
  'payload': {'tier': 'UncensoredCompact',
              'name': 'Qwen 3.5 35B Uncensored (Compact)',
              'provider': 'HauhauCS',
              'filename': 'Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf',
              'disk_size_gb': 11.0,
              'ram_required_gb': 14.0,
              'text_rating': 4,
              'code_rating': 3,
              'vision_rating': 3,
              'tool_calling_rating': 3,
              'speed': 'Medium',
              'description': 'Uncensored Qwen3.5-35B MoE (abliterated). No refusals. Essential for '
                             'sensitive monitoring, analysis, and tasks standard models decline.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive',
              'is_uncensored': True,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive/resolve/main/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 11811000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'IQ2_M',
                            'filename': 'Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf',
                            'disk_size_gb': 11.0,
                            'ram_required_gb': 14.0,
                            'hf_url': 'https://huggingface.co/HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive/resolve/main/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf',
                            'expected_size_bytes': 11811000000,
                            'mmproj_filename': '',
                            'mmproj_url': '',
                            'mmproj_expected_size_bytes': 0},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Balanced',
                            'quant': 'IQ4_XS',
                            'filename': 'Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf',
                            'disk_size_gb': 18.0,
                            'ram_required_gb': 22.0,
                            'hf_url': 'https://huggingface.co/HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive/resolve/main/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf',
                            'expected_size_bytes': 19327000000,
                            'mmproj_filename': '',
                            'mmproj_url': '',
                            'mmproj_expected_size_bytes': 0}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 280,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'UncensoredBalanced',
  'payload': {'tier': 'UncensoredBalanced',
              'name': 'Qwen 3.5 35B Uncensored (Balanced)',
              'provider': 'HauhauCS',
              'filename': 'Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf',
              'disk_size_gb': 18.0,
              'ram_required_gb': 22.0,
              'text_rating': 4,
              'code_rating': 3,
              'vision_rating': 3,
              'tool_calling_rating': 3,
              'speed': 'GPU recommended',
              'description': 'Higher quality uncensored Qwen3.5-35B MoE (abliterated). Better '
                             'outputs for sensitive analysis tasks.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive',
              'is_uncensored': True,
              'is_server_grade': False,
              'hf_url': 'https://huggingface.co/HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive/resolve/main/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 19327000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': [{'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Compact',
                            'quant': 'IQ2_M',
                            'filename': 'Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf',
                            'disk_size_gb': 11.0,
                            'ram_required_gb': 14.0,
                            'hf_url': 'https://huggingface.co/HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive/resolve/main/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ2_M.gguf',
                            'expected_size_bytes': 11811000000,
                            'mmproj_filename': '',
                            'mmproj_url': '',
                            'mmproj_expected_size_bytes': 0},
                           {'hf_parts': [],
                            'hf_part_sizes': [],
                            'label': 'Balanced',
                            'quant': 'IQ4_XS',
                            'filename': 'Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf',
                            'disk_size_gb': 18.0,
                            'ram_required_gb': 22.0,
                            'hf_url': 'https://huggingface.co/HauhauCS/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive/resolve/main/Qwen3.5-35B-A3B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf',
                            'expected_size_bytes': 19327000000,
                            'mmproj_filename': '',
                            'mmproj_url': '',
                            'mmproj_expected_size_bytes': 0}]},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 290,
  'notes': 'multi-variant model: artifact URLs live on payload.variants[].hf_url'},
 {'key': 'Server',
  'payload': {'tier': 'Server',
              'name': 'Llama 3.3 70B',
              'provider': 'Meta',
              'filename': 'Llama-3.3-70B-Instruct-Q4_K_M.gguf',
              'disk_size_gb': 42.5,
              'ram_required_gb': 48.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 0,
              'tool_calling_rating': 4,
              'speed': 'Server GPU',
              'description': "Meta's best dense 70B. Rivals much larger models on benchmarks. "
                             'Requires 48 GB+ VRAM.',
              'knowledge_cutoff': 'Dec 2023',
              'hf_model_card_url': 'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct',
              'is_uncensored': False,
              'is_server_grade': True,
              'hf_url': 'https://huggingface.co/unsloth/Llama-3.3-70B-Instruct-GGUF/resolve/main/Llama-3.3-70B-Instruct-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 45618000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Llama-3.3-70B-Instruct-GGUF/resolve/main/Llama-3.3-70B-Instruct-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 45618000000,
  'sort_order': 300},
 {'key': 'Server2',
  'payload': {'tier': 'Server2',
              'name': 'Qwen 3.5 122B A10B',
              'provider': 'Alibaba',
              'filename': 'Qwen3.5-122B-A10B-UD-IQ2_M.gguf',
              'disk_size_gb': 39.1,
              'ram_required_gb': 48.0,
              'text_rating': 5,
              'code_rating': 5,
              'vision_rating': 4,
              'tool_calling_rating': 5,
              'speed': 'Server GPU',
              'description': '122B MoE, only 10B active. Near-frontier quality accessible on 48 '
                             'GB+ servers. Arena rank #16 globally.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3.5-122B-A10B',
              'is_uncensored': False,
              'is_server_grade': True,
              'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-122B-A10B-GGUF/resolve/main/Qwen3.5-122B-A10B-UD-IQ2_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 41980000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Qwen3.5-122B-A10B-GGUF/resolve/main/Qwen3.5-122B-A10B-UD-IQ2_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 41980000000,
  'sort_order': 310},
 {'key': 'Server3',
  'payload': {'tier': 'Server3',
              'name': 'Mistral Small 4 119B',
              'provider': 'Mistral',
              'filename': 'Mistral-Small-4-119B-2603-Q4_K_M.gguf',
              'disk_size_gb': 72.6,
              'ram_required_gb': 80.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 3,
              'tool_calling_rating': 4,
              'speed': 'Server GPU',
              'description': "Mistral's latest unified MoE — reasoning + multimodal + coding in "
                             'one 256k-context model. Released March 2026.',
              'knowledge_cutoff': 'Mar 2026',
              'hf_model_card_url': 'https://huggingface.co/mistralai/Mistral-Small-4-119B-2603',
              'is_uncensored': False,
              'is_server_grade': True,
              'hf_url': 'https://huggingface.co/unsloth/Mistral-Small-4-119B-2603-GGUF/resolve/main/Mistral-Small-4-119B-2603-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 77952000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Mistral-Small-4-119B-2603-GGUF/resolve/main/Mistral-Small-4-119B-2603-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 77952000000,
  'sort_order': 320},
 {'key': 'Server4',
  'payload': {'tier': 'Server4',
              'name': 'Llama 4 Scout 17B',
              'provider': 'Meta',
              'filename': 'Llama-4-Scout-17B-16E-Instruct-Q4_K_M-00001-of-00002.gguf',
              'disk_size_gb': 67.5,
              'ram_required_gb': 80.0,
              'text_rating': 4,
              'code_rating': 4,
              'vision_rating': 4,
              'tool_calling_rating': 4,
              'speed': 'Server GPU',
              'description': "Meta's Llama 4 MoE with unprecedented 10M token context. Multimodal "
                             '(text + image). 109B total / 17B active.',
              'knowledge_cutoff': 'Mar 2025',
              'hf_model_card_url': 'https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct',
              'is_uncensored': False,
              'is_server_grade': True,
              'hf_url': 'https://huggingface.co/unsloth/Llama-4-Scout-17B-16E-Instruct-GGUF/resolve/main/Llama-4-Scout-17B-16E-Instruct-Q4_K_M-00001-of-00002.gguf',
              'hf_parts': ['https://huggingface.co/unsloth/Llama-4-Scout-17B-16E-Instruct-GGUF/resolve/main/Llama-4-Scout-17B-16E-Instruct-Q4_K_M-00002-of-00002.gguf'],
              'context_length': 131072,
              'expected_size_bytes': 36283000000,
              'hf_part_sizes': [31217000000],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Llama-4-Scout-17B-16E-Instruct-GGUF/resolve/main/Llama-4-Scout-17B-16E-Instruct-Q4_K_M-00001-of-00002.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 36283000000,
  'sort_order': 330},
 {'key': 'Server5',
  'payload': {'tier': 'Server5',
              'name': 'GPT OSS 120B',
              'provider': 'OpenAI',
              'filename': 'openai_gpt-oss-120b-Q4_K_M.gguf',
              'disk_size_gb': 88.0,
              'ram_required_gb': 96.0,
              'text_rating': 5,
              'code_rating': 5,
              'vision_rating': 0,
              'tool_calling_rating': 5,
              'speed': 'Server GPU',
              'description': "OpenAI's largest open-source model. Near o4-mini parity. Best "
                             'open-weight reasoning model available. 128k context.',
              'knowledge_cutoff': 'Mid 2025',
              'hf_model_card_url': 'https://huggingface.co/openai/gpt-oss-120b',
              'is_uncensored': False,
              'is_server_grade': True,
              'hf_url': 'https://huggingface.co/bartowski/openai_gpt-oss-120b-GGUF/resolve/main/openai_gpt-oss-120b-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 131072,
              'expected_size_bytes': 94489000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/openai_gpt-oss-120b-GGUF/resolve/main/openai_gpt-oss-120b-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 94489000000,
  'sort_order': 340},
 {'key': 'Server6',
  'payload': {'tier': 'Server6',
              'name': 'Qwen 3.5 397B A17B',
              'provider': 'Alibaba',
              'filename': 'Qwen3.5-397B-A17B-UD-IQ2_XXS.gguf',
              'disk_size_gb': 115.0,
              'ram_required_gb': 128.0,
              'text_rating': 5,
              'code_rating': 5,
              'vision_rating': 5,
              'tool_calling_rating': 5,
              'speed': 'Server GPU',
              'description': 'The best open-source model in the world. Arena rank #3 globally. '
                             '397B total / 17B active MoE. Near-frontier on every task.',
              'knowledge_cutoff': 'Feb 2026',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3.5-397B-A17B',
              'is_uncensored': False,
              'is_server_grade': True,
              'hf_url': 'https://huggingface.co/unsloth/Qwen3.5-397B-A17B-GGUF/resolve/main/Qwen3.5-397B-A17B-UD-IQ2_XXS.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 123476000000,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/unsloth/Qwen3.5-397B-A17B-GGUF/resolve/main/Qwen3.5-397B-A17B-UD-IQ2_XXS.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 123476000000,
  'sort_order': 350},
 {'key': 'Server7',
  'payload': {'tier': 'Server7',
              'name': 'Qwen 3 Next 80B A3B',
              'provider': 'Alibaba',
              'filename': 'Qwen_Qwen3-Next-80B-A3B-Instruct-Q4_K_M.gguf',
              'disk_size_gb': 48.7,
              'ram_required_gb': 56.0,
              'text_rating': 5,
              'code_rating': 4,
              'vision_rating': 0,
              'tool_calling_rating': 5,
              'speed': 'Server GPU',
              'description': '80B MoE with only ~3B active. Fast long-context server model — sits '
                             'between Scout and Qwen 3.5 122B A10B.',
              'knowledge_cutoff': 'Sep 2025',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3-Next-80B-A3B-Instruct',
              'is_uncensored': False,
              'is_server_grade': True,
              'hf_url': 'https://huggingface.co/bartowski/Qwen_Qwen3-Next-80B-A3B-Instruct-GGUF/resolve/main/Qwen_Qwen3-Next-80B-A3B-Instruct-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 48727677408,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/Qwen_Qwen3-Next-80B-A3B-Instruct-GGUF/resolve/main/Qwen_Qwen3-Next-80B-A3B-Instruct-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 48727677408,
  'sort_order': 360},
 {'key': 'Server8',
  'payload': {'tier': 'Server8',
              'name': 'Qwen 3 Coder Next',
              'provider': 'Alibaba',
              'filename': 'Qwen_Qwen3-Coder-Next-Q4_K_M.gguf',
              'disk_size_gb': 48.7,
              'ram_required_gb': 56.0,
              'text_rating': 4,
              'code_rating': 5,
              'vision_rating': 0,
              'tool_calling_rating': 5,
              'speed': 'Server GPU',
              'description': 'Server-grade coding MoE (~80B / ~3B active). Best practical coding '
                             'beast for Mac Studio / 64GB+ boxes.',
              'knowledge_cutoff': 'Jan 2026',
              'hf_model_card_url': 'https://huggingface.co/Qwen/Qwen3-Coder-Next',
              'is_uncensored': False,
              'is_server_grade': True,
              'hf_url': 'https://huggingface.co/bartowski/Qwen_Qwen3-Coder-Next-GGUF/resolve/main/Qwen_Qwen3-Coder-Next-Q4_K_M.gguf',
              'hf_parts': [],
              'context_length': 262144,
              'expected_size_bytes': 48727680704,
              'hf_part_sizes': [],
              'mmproj_filename': '',
              'mmproj_url': '',
              'mmproj_expected_size_bytes': 0,
              'variants': []},
  'artifact_url': 'https://huggingface.co/bartowski/Qwen_Qwen3-Coder-Next-GGUF/resolve/main/Qwen_Qwen3-Coder-Next-Q4_K_M.gguf',
  'artifact_sha256': None,
  'artifact_size_bytes': 48727680704,
  'sort_order': 370}]

# Source: desktop/src-tauri/src/transcription/model_selector.rs + downloader.rs
COMPILED_WHISPER_MODEL_ENTRIES: list[dict[str, Any]] = [{'key': 'ggml-tiny.en.bin',
  'payload': {'tier': 'Low',
              'filename': 'ggml-tiny.en.bin',
              'download_size_mb': 75,
              'ram_required_mb': 390,
              'relative_speed': '~32x realtime',
              'accuracy': 'Good (~5.7% WER)',
              'description': 'Fastest, lowest resource usage. Best for older or low-RAM machines.',
              'download_url': 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin',
              'role': 'transcription'},
  'artifact_url': 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin',
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 0},
 {'key': 'ggml-base.en.bin',
  'payload': {'tier': 'Default',
              'filename': 'ggml-base.en.bin',
              'download_size_mb': 142,
              'ram_required_mb': 506,
              'relative_speed': '~16x realtime',
              'accuracy': 'Very good (~4.2% WER)',
              'description': 'Recommended for most users. Best balance of speed and accuracy.',
              'download_url': 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin',
              'role': 'transcription'},
  'artifact_url': 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin',
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 10},
 {'key': 'ggml-small.en.bin',
  'payload': {'tier': 'High',
              'filename': 'ggml-small.en.bin',
              'download_size_mb': 466,
              'ram_required_mb': 1024,
              'relative_speed': '~6x realtime',
              'accuracy': 'Excellent (~2.9% WER)',
              'description': 'Highest accuracy. Requires 8GB+ RAM or GPU acceleration.',
              'download_url': 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin',
              'role': 'transcription'},
  'artifact_url': 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin',
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 20},
 {'key': 'ggml-silero-v6.2.0.bin',
  'payload': {'tier': None,
              'filename': 'ggml-silero-v6.2.0.bin',
              'download_size_mb': None,
              'ram_required_mb': None,
              'relative_speed': None,
              'accuracy': None,
              'description': 'Silero VAD model required for streaming transcription (no GGML '
                             'header; validated by size > 50KB).',
              'download_url': 'https://huggingface.co/ggml-org/whisper-vad/resolve/main/ggml-silero-v6.2.0.bin',
              'role': 'vad'},
  'artifact_url': 'https://huggingface.co/ggml-org/whisper-vad/resolve/main/ggml-silero-v6.2.0.bin',
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 30,
  'notes': 'VAD companion model; source defines only filename + base URL (downloader.rs), struct '
           'fields null.'}]

# Source: desktop/src/lib/system-prompts.ts
COMPILED_SYSTEM_PROMPT_ENTRIES: list[dict[str, Any]] = [{'key': 'builtin-assistant',
  'payload': {'id': 'builtin-assistant',
              'name': 'Helpful Assistant',
              'content': 'You are a helpful, accurate, and concise assistant.\n'
                         '\n'
                         'Rules:\n'
                         '- Answer the question directly — no preamble, no filler\n'
                         "- If you don't know something, say so — do not guess or fabricate\n"
                         '- Keep responses as short as they can be while still being complete\n'
                         '- Match the tone of the question: casual gets casual, technical gets '
                         'technical\n',
              'category': 'General'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 0},
 {'key': 'builtin-transcript-polish',
  'payload': {'id': 'builtin-transcript-polish',
              'name': 'Transcript Polish',
              'content': 'You are a Transcript Cleanup Specialist. You take raw, messy transcripts '
                         'and produce clean, polished text.\n'
                         '\n'
                         'Your job is simple: clean up the transcript while keeping the original '
                         'meaning completely intact.\n'
                         '\n'
                         'What to fix:\n'
                         '- Transcription errors (misheard words, garbled phrases)\n'
                         '- Punctuation, grammar, and spelling\n'
                         '- Filler words like "um," "uh," "you know," "like" when used as filler\n'
                         '- Repeated or duplicated words that are clearly stutters or '
                         'transcription artifacts\n'
                         '- Run-on sentences — break them into proper sentences\n'
                         '- Walls of text — break them into shorter paragraphs\n'
                         '\n'
                         'What to improve:\n'
                         '- Add structure where it helps: short paragraphs, bullet points, '
                         'numbered lists, headers\n'
                         '- Favor shorter paragraphs over long ones\n'
                         '- Make sentences clear and readable\n'
                         '\n'
                         'What NOT to do:\n'
                         '- Do not change the meaning of anything\n'
                         '- Do not add information that was not in the original\n'
                         '- Do not remove meaningful content\n'
                         '- Do not make the text more formal unless it was already formal — '
                         "preserve the speaker's natural voice and tone\n"
                         '- Do not summarize or condense — keep all the substance\n'
                         '\n'
                         'When something is genuinely ambiguous and you cannot tell what was '
                         'meant, use this format: [OPTION A: first interpretation] / [OPTION B: '
                         'second interpretation]. Only do this for important ambiguities where the '
                         'meaning would change.\n',
              'category': 'Voice'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 10},
 {'key': 'builtin-summarize',
  'payload': {'id': 'builtin-summarize',
              'name': 'Summarize',
              'content': 'You are a summarization specialist. You take text and produce a concise '
                         'summary that captures every key point.\n'
                         '\n'
                         'Rules:\n'
                         '- Include all important information — do not skip key points\n'
                         '- Use clear, structured prose — not a rewrite of the original\n'
                         '- Use bullet points only if the source material is already a list\n'
                         '- Do not add an introduction, conclusion, or commentary\n'
                         '- Do not add opinions or information that was not in the original\n'
                         '- Output only the summary — nothing else\n',
              'category': 'Writing'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 20},
 {'key': 'builtin-explain',
  'payload': {'id': 'builtin-explain',
              'name': 'Explain Simply',
              'content': 'You are an explanation specialist. You take complex topics and make them '
                         'easy to understand for someone with no background.\n'
                         '\n'
                         'Rules:\n'
                         '- Use plain, simple language — no jargon\n'
                         '- Use short sentences and concrete examples\n'
                         '- If a technical term is unavoidable, define it immediately in '
                         'parentheses\n'
                         '- Build understanding step by step — start with the basics before '
                         'details\n'
                         '- Do not assume the reader knows anything about the topic\n'
                         '- Do not add unnecessary disclaimers or filler\n',
              'category': 'Writing'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 30},
 {'key': 'builtin-code-review',
  'payload': {'id': 'builtin-code-review',
              'name': 'Code Review',
              'content': 'You are a code review specialist. You analyze code for correctness, '
                         'readability, and potential bugs.\n'
                         '\n'
                         'Rules:\n'
                         '- List each issue as a bullet point with a brief explanation\n'
                         '- For each issue, suggest a fix or improvement\n'
                         '- Focus on things that matter: bugs, logic errors, edge cases, '
                         'readability problems\n'
                         '- Do not nitpick style preferences (formatting, naming conventions) '
                         'unless they hurt readability\n'
                         '- If the code looks good, say so briefly — do not invent problems\n'
                         '- Do not rewrite the entire code unless asked to\n',
              'category': 'Development'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 40},
 {'key': 'builtin-brainstorm',
  'payload': {'id': 'builtin-brainstorm',
              'name': 'Brainstorm',
              'content': 'You are a brainstorming specialist. You generate creative, diverse ideas '
                         'for a given topic.\n'
                         '\n'
                         'Rules:\n'
                         '- Aim for breadth — cover a wide range of approaches, both conventional '
                         'and unconventional\n'
                         '- Present each idea as a short bullet point (1-2 sentences max)\n'
                         '- Do not explain or justify ideas unless asked — just list them\n'
                         '- Do not repeat the same idea in different words\n'
                         '- Do not filter ideas for feasibility unless asked — include bold and '
                         'unusual ones\n'
                         '- Generate at least 8 ideas unless the topic is very narrow\n',
              'category': 'Creative'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 50},
 {'key': 'builtin-voice-assistant',
  'payload': {'id': 'builtin-voice-assistant',
              'name': 'Voice Assistant',
              'content': 'You are a voice assistant. Your responses are spoken aloud by a '
                         'text-to-speech engine, so they must be short and conversational.\n'
                         '\n'
                         'Critical rules:\n'
                         '- Keep every response under 3 sentences unless the question strictly '
                         'requires more\n'
                         '- Never use bullet points, numbered lists, markdown, code blocks, or '
                         'headers — plain prose only\n'
                         '- Never say "Certainly!", "Great question!", "Of course!" or any filler '
                         'opener — just answer directly\n'
                         '- If you need to give a long answer, summarize it in 2 sentences and '
                         'offer to elaborate\n'
                         '- Match the pace of conversation: short question → short answer\n'
                         "- If you don't know something, say so in one sentence\n",
              'category': 'Voice'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 60}]

# Source: desktop/src/lib/api-key-patterns.ts
COMPILED_API_KEY_PROVIDER_ENTRIES: list[dict[str, Any]] = [{'key': 'openai',
  'payload': {'names': ['openai', 'open_ai', 'oai', 'openai_api'],
              'env_var_names': ['OPENAI_API_KEY',
                                'OPENAI_KEY',
                                'OAI_API_KEY',
                                'OAI_KEY',
                                'OPENAI_SECRET'],
              'label': 'OpenAI'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 0},
 {'key': 'anthropic',
  'payload': {'names': ['anthropic', 'claude', 'claude_ai'],
              'env_var_names': ['ANTHROPIC_API_KEY',
                                'ANTHROPIC_KEY',
                                'CLAUDE_API_KEY',
                                'CLAUDE_KEY'],
              'label': 'Anthropic'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 10},
 {'key': 'google',
  'payload': {'names': ['google', 'gemini', 'google_ai', 'googleai', 'gemini_ai', 'google_gemini'],
              'env_var_names': ['GOOGLE_API_KEY',
                                'GEMINI_API_KEY',
                                'GOOGLE_GEMINI_API_KEY',
                                'GOOGLEAI_API_KEY',
                                'GOOGLE_GENERATIVE_AI_API_KEY',
                                'GOOGLE_AI_API_KEY'],
              'label': 'Google'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 20},
 {'key': 'huggingface',
  'payload': {'names': ['huggingface', 'hf', 'hf_hub', 'hugging_face', 'huggingface_hub'],
              'env_var_names': ['HUGGING_FACE_HUB_TOKEN',
                                'HF_TOKEN',
                                'HUGGINGFACE_TOKEN',
                                'HUGGING_FACE_TOKEN'],
              'label': 'Hugging Face'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 30},
 {'key': 'civitai',
  'payload': {'names': ['civitai', 'civit_ai'],
              'env_var_names': ['CIVITAI_API_KEY', 'CIVITAI_API_TOKEN', 'CIVITAI_TOKEN'],
              'label': 'Civitai'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 40},
 {'key': 'groq',
  'payload': {'names': ['groq', 'groq_ai'],
              'env_var_names': ['GROQ_API_KEY', 'GROQ_KEY'],
              'label': 'Groq'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 50},
 {'key': 'together',
  'payload': {'names': ['together', 'togetherai', 'together_ai', 'together_xyz'],
              'env_var_names': ['TOGETHER_API_KEY', 'TOGETHER_AI_API_KEY', 'TOGETHERAI_API_KEY'],
              'label': 'Together AI'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 60},
 {'key': 'xai',
  'payload': {'names': ['xai', 'x_ai', 'grok', 'grok_ai'],
              'env_var_names': ['XAI_API_KEY', 'XAI_KEY', 'GROK_API_KEY', 'X_AI_API_KEY'],
              'label': 'xAI'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 70},
 {'key': 'cerebras',
  'payload': {'names': ['cerebras', 'cerebras_ai'],
              'env_var_names': ['CEREBRAS_API_KEY', 'CEREBRAS_KEY'],
              'label': 'Cerebras'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 80},
 {'key': 'elevenlabs',
  'payload': {'names': ['elevenlabs', 'eleven_labs', '11labs'],
              'env_var_names': ['ELEVENLABS_API_KEY', 'ELEVEN_LABS_API_KEY', 'ELEVENLABS_KEY'],
              'label': 'ElevenLabs'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 90},
 {'key': 'fastino',
  'payload': {'names': ['fastino', 'pioneer'],
              'env_var_names': ['FASTINO_API_KEY', 'PIONEER_API_KEY'],
              'label': 'Fastino'},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 100},
 {'key': 'global-strip-lists',
  'payload': {'strip_prefixes': ['VITE_',
                                 'NEXT_PUBLIC_',
                                 'REACT_APP_',
                                 'EXPO_PUBLIC_',
                                 'NUXT_PUBLIC_',
                                 'PUBLIC_',
                                 'APP_'],
              'strip_suffixes': ['_API_KEY',
                                 '_APIKEY',
                                 '_SECRET_KEY',
                                 '_SECRET',
                                 '_KEY',
                                 '_TOKEN',
                                 '_ACCESS_TOKEN',
                                 '_AUTH_TOKEN',
                                 '_AUTH_KEY',
                                 '_CREDENTIAL',
                                 '_CREDENTIALS']},
  'artifact_url': None,
  'artifact_sha256': None,
  'artifact_size_bytes': None,
  'sort_order': 110,
  'notes': 'GLOBAL_STRIP_PREFIXES + GLOBAL_STRIP_SUFFIXES (env-var noise stripped before provider '
           "matching). Key '_strip_lists' impossible: DB key regex forbids leading underscore."}]

