"""Compile-time bootstrap configuration baked into the PyInstaller binary by CI.

AUTO-GENERATED by scripts/write_bundled_config.py — do not edit manually.
To regenerate: python scripts/write_bundled_config.py
"""

SUPABASE_URL: str = 'https://db.matrxserver.com'
SUPABASE_PUBLISHABLE_KEY: str = 'sb_publishable_scm0jzEJiFUB5ItiqOx5Fg_8BOjB6oA'


def apply() -> None:
    """Inject bundled Supabase bootstrap config if not already set."""
    import os

    _vals = {
        "SUPABASE_URL": SUPABASE_URL,
        "SUPABASE_PUBLISHABLE_KEY": SUPABASE_PUBLISHABLE_KEY,
    }
    for key, val in _vals.items():
        if val and not os.environ.get(key):
            os.environ[key] = val
