-- matrx-local tool registry changeset
--
-- No pending SQL changeset.
--
-- Last applied via Supabase MCP:
--   2026-07-14: local_extract_entities + local_extract_pii
--
-- Verification after apply:
--   uv run --no-sync python -m app.tools.tool_sync status
--   RESULT: code catalog (115) vs cloud canon (115), no drift detected.
--
-- Generate a new applyable changeset only when `tool_sync status` reports
-- drift:
--   uv run --no-sync python -m app.tools.tool_sync emit-changeset
