import {afterEach,expect,it,vi} from "vitest";
const mocks=vi.hoisted(()=>({listener:undefined as any,snapshot:{signed_in:true,user_id:"actor-a",email:"a@test",state:"signed_in",state_reason:null,since:null,next_attempt_at:null,cloud_state_write_pending:false},prepare:"unavailable" as "unavailable"|"aligned",aligns:0}));
vi.mock("@/lib/custodian",()=>({currentSession:()=>mocks.snapshot,getSession:vi.fn(async()=>mocks.snapshot),subscribeSession:vi.fn((cb)=>{mocks.listener=cb;return()=>undefined;}),sessionToMatrx:(s:any)=>s.signed_in?{user:{id:s.user_id,email:s.email}}:null,getAuthedSession:vi.fn(async()=>({user:{id:"actor-a"}})),getToken:vi.fn(async()=>"daemon-token")}));
vi.mock("@/lib/sidecar",()=>({invalidateNativeVaultHostActor:async()=>"unsupported_platform",reconcileNativeVaultHostActor:async()=>"unsupported_platform"}));
vi.mock("@/lib/api",()=>({engine:{prepareSessionTransition:async()=>{mocks.aligns++;return mocks.prepare==="aligned"?{status:"aligned",origin:"http://engine",generation:"g",credentialRevision:0,subject:"actor-a"}:{status:"unavailable"};}}}));
afterEach(()=>{vi.resetModules();mocks.listener=undefined;mocks.prepare="unavailable";mocks.aligns=0;});
it("does not release an anonymous token while initial alignment is unavailable",async()=>{const auth=await import("./native-vault-auth");auth.subscribeNativeVaultHostEvents(()=>undefined);await Promise.resolve();await new Promise(r=>setTimeout(r,0));await expect(auth.resolveNativeVaultEngineAccessToken()).rejects.toThrow("connection to this engine");});
it("aligns after discovery before releasing a signed-in daemon token",async()=>{const auth=await import("./native-vault-auth");auth.subscribeNativeVaultHostEvents(()=>undefined);await Promise.resolve();await new Promise(r=>setTimeout(r,0));mocks.prepare="aligned";await expect(auth.resolveNativeVaultEngineAccessToken()).resolves.toBe("daemon-token");expect(mocks.aligns).toBe(2);});
it("shares one post-discovery alignment across thirty concurrent token reads",async()=>{const auth=await import("./native-vault-auth");auth.subscribeNativeVaultHostEvents(()=>undefined);await Promise.resolve();await new Promise(r=>setTimeout(r,0));mocks.prepare="aligned";await expect(Promise.all(Array.from({length:30},()=>auth.resolveNativeVaultEngineAccessToken()))).resolves.toHaveLength(30);expect(mocks.aligns).toBe(2);});
