/**
 * The desktop app's Mandate vocabulary.
 *
 * 🚨 THIS FILE NO LONGER NAMES A MANDATE. The key below comes from
 * `@ai-matrx/agents/mandates` (0.10.0), generated by THE ONE GENERATOR from
 * aidream's own `declared_mandates()`. The hand-typed literal that used to live
 * here — and the "mirror of matrx-extend's file" note above it — were the
 * defect: a rename or a retirement on the server turned into a 404 nobody saw.
 * A key that stops being declared now fails TYPE-CHECK here.
 *
 * A Mandate is the platform's named answer to "which agent runs this step" —
 * the agent lives in the DATABASE; this file only names the job. Never an
 * agent UUID here. SoR: common-docs/systems/mandates/STATE.md (+ RUNTIME.md).
 *
 * What this file still owns is the `mandate:` REF — the desktop's own stable UI
 * identity for a Mandate-backed choice, stored in settings beside real agent
 * ids. That prefix is a client-side convention, not a platform key.
 */

import { MANDATE_KEYS, type MandateKey } from "@ai-matrx/agents/mandates";

/** Canonical server-resolved target for a brand-new desktop Cloud Chat. */
export const DEFAULT_CHAT_MANDATE_KEY: MandateKey =
  MANDATE_KEYS.local__cloud_chat;

/**
 * Stable UI identity for a Mandate-backed choice. This is not an agent id and
 * is never sent to an agent-id route; the run path uses the mandate key.
 */
export const DEFAULT_CHAT_MANDATE_REF = `mandate:${DEFAULT_CHAT_MANDATE_KEY}` as const;

export function isMandateAgentRef(value: string | null | undefined): boolean {
  return typeof value === "string" && value.startsWith("mandate:");
}

/**
 * The key inside a `mandate:` ref, or `null` if it is not one.
 *
 * 🚨 This deliberately does NOT narrow to `MandateKey`. It decides which DOOR a
 * stored target goes through (`/ai/mandates/{key}` vs the agent-id route), and
 * the SERVER — not this build's snapshot of the vocabulary — is the authority
 * on what exists. Narrowing here would send a ref naming a mandate declared
 * after this version shipped to the agent door, which fails naming the wrong
 * thing. The vocabulary binds the keys we NAME (above); this is a parse of a
 * ref we stored.
 */
export function mandateKeyFromAgentRef(
  value: string | null | undefined,
): string | null {
  if (!isMandateAgentRef(value)) return null;
  const key = value?.slice("mandate:".length) ?? "";
  return key.length > 0 ? key : null;
}
