//! Bake the Supabase bootstrap pair into the daemon binary.
//!
//! The configuration posture in `matrx-local/CLAUDE.md` puts non-secret runtime values (URLs,
//! flags, min versions) in remote app config with a **compiled-in fallback**, and forbids any
//! shipped behaviour depending on a `.env`. The bootstrap pair — the Supabase URL and the
//! publishable key — is the one value that cannot come from remote app config, because it is what
//! *fetches* remote app config.
//!
//! The repository already has exactly one source of truth for it: `app/bundled_config.py`,
//! generated by `scripts/write_bundled_config.py` from CI secrets. This script reads that file
//! rather than introducing a second copy the two could drift between.
//!
//! **A parse failure fails the build.** A default here would be a silent stand-in for a value the
//! whole sign-in flow depends on.

use std::path::PathBuf;

#[path = "src/version_metadata.rs"]
mod version_metadata;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let bundled = manifest
        .join("..")
        .join("..")
        .join("app")
        .join("bundled_config.py");
    println!("cargo:rerun-if-changed={}", bundled.display());
    println!("cargo:rerun-if-env-changed=MATRX_SUPABASE_URL");
    println!("cargo:rerun-if-env-changed=MATRX_SUPABASE_PUBLISHABLE_KEY");

    let tauri_config = manifest
        .join("..")
        .join("..")
        .join("desktop")
        .join("src-tauri")
        .join("tauri.conf.json");
    println!("cargo:rerun-if-changed={}", tauri_config.display());
    let app_version_source = std::fs::read_to_string(&tauri_config).unwrap_or_else(|error| {
        panic!(
            "matrx-syncd cannot be built without the canonical desktop app version. {} could not be read: {error}",
            tauri_config.display()
        )
    });
    let app_version = version_metadata::app_version_from_tauri_config(&app_version_source)
        .unwrap_or_else(|error| {
            panic!("matrx-syncd cannot embed its desktop app version: {error}")
        });
    println!("cargo:rustc-env=MATRX_SYNCD_APP_VERSION={app_version}");

    let source = std::fs::read_to_string(&bundled).unwrap_or_else(|e| {
        panic!(
            "matrx-syncd cannot be built without the Supabase bootstrap pair. {} could not be \
             read: {e}. Regenerate it with `python scripts/write_bundled_config.py`.",
            bundled.display()
        )
    });

    let url = extract(&source, "SUPABASE_URL");
    let key = extract(&source, "SUPABASE_PUBLISHABLE_KEY");

    // CI and a developer may override without editing the checked-in file; an override that is
    // present but empty is a mistake, not a request to ship an empty value.
    let url = std::env::var("MATRX_SUPABASE_URL").unwrap_or(url);
    let key = std::env::var("MATRX_SUPABASE_PUBLISHABLE_KEY").unwrap_or(key);
    assert!(
        url.starts_with("https://"),
        "the Supabase URL baked into matrx-syncd is {url:?}, which is not an https URL"
    );
    assert!(
        !key.is_empty(),
        "the Supabase publishable key baked into matrx-syncd is empty"
    );

    println!("cargo:rustc-env=MATRX_SYNCD_SUPABASE_URL={url}");
    println!("cargo:rustc-env=MATRX_SYNCD_SUPABASE_PUBLISHABLE_KEY={key}");
}

/// Pull `NAME: str = '…'` out of the generated Python module.
fn extract(source: &str, name: &str) -> String {
    for line in source.lines() {
        let Some(rest) = line.strip_prefix(&format!("{name}: str = ")) else {
            continue;
        };
        let rest = rest.trim();
        let quote = rest.chars().next().unwrap_or(' ');
        if quote == '\'' || quote == '"' {
            if let Some(value) = rest[1..].split(quote).next() {
                return value.to_string();
            }
        }
    }
    panic!(
        "app/bundled_config.py does not declare {name} in the shape `{name}: str = '…'`; \
         matrx-syncd reads it there so the two never drift apart"
    );
}
