#!/usr/bin/env python3
"""Write Supabase bootstrap config into app/bundled_config.py before PyInstaller.

Called by CI (and optionally by a developer locally) to bake the public
Supabase connection values needed to fetch remote app configuration before a
user signs in. Runtime app configuration, including service URLs, is read from
the remote app-config row and its last-good local cache.

Usage:
    python scripts/write_bundled_config.py

Required environment variables (read from CI secrets / local .env):
    SUPABASE_URL                 — e.g. https://db.matrxserver.com
    SUPABASE_PUBLISHABLE_KEY     — the publishable key from Supabase

Exit code 0 on success, 1 if any required var is missing.
"""

import os
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "app" / "bundled_config.py"


def render_bundled_config(*, supabase_url: str, supabase_key: str) -> str:
    """Return the generated module containing only immutable bootstrap values."""
    return textwrap.dedent(f'''\
        """Compile-time bootstrap configuration baked into the PyInstaller binary by CI.

        AUTO-GENERATED by scripts/write_bundled_config.py — do not edit manually.
        To regenerate: python scripts/write_bundled_config.py
        """

        SUPABASE_URL: str = {supabase_url!r}
        SUPABASE_PUBLISHABLE_KEY: str = {supabase_key!r}


        def apply() -> None:
            """Inject bundled Supabase bootstrap config if not already set."""
            import os

            _vals = {{
                "SUPABASE_URL": SUPABASE_URL,
                "SUPABASE_PUBLISHABLE_KEY": SUPABASE_PUBLISHABLE_KEY,
            }}
            for key, val in _vals.items():
                if val and not os.environ.get(key):
                    os.environ[key] = val
    ''')


def main() -> int:
    # Load .env so running locally also works.
    env_file = ROOT / ".env"
    if env_file.exists():
        from dotenv import load_dotenv

        load_dotenv(dotenv_path=env_file)

    supabase_url = os.environ.get("SUPABASE_URL", "").strip()
    supabase_key = os.environ.get("SUPABASE_PUBLISHABLE_KEY", "").strip()
    missing = [
        key
        for key, value in [
            ("SUPABASE_URL", supabase_url),
            ("SUPABASE_PUBLISHABLE_KEY", supabase_key),
        ]
        if not value
    ]
    if missing:
        print(f"ERROR: Missing required env vars: {', '.join(missing)}", file=sys.stderr)
        print("Set them in your environment or in the root .env file.", file=sys.stderr)
        return 1

    TARGET.write_text(
        render_bundled_config(supabase_url=supabase_url, supabase_key=supabase_key),
        encoding="utf-8",
    )
    print(f"✅  Wrote bundled config to {TARGET}")
    print(f"   SUPABASE_URL             = {supabase_url}")
    print(f"   SUPABASE_PUBLISHABLE_KEY = {'*' * 8}{supabase_key[-6:]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
