"""Codex artifacts recorded at HOOK TIME reach the same lane and the same screen.

Codex stopped naming the files it writes: measured on this Mac 2026-09-17,
0 of the 4,492 rollouts from August 2026 onward contain a single
``apply_patch``, against 523,106 shell/``exec`` calls whose writes Codex
records nowhere (lane CS-31). Reading the rollout harder cannot fix that — the
fact is not in the file. The AI Matrx plugin for Codex now records each turn's
writes as they happen and leaves a DECLARATION in its own durable plugin data
directory; this module's source reads them (lane CS-34).

``tests/fixtures/codex/hook-declaration.writes.json`` is not hand-written. It
is the byte output of the REAL plugin emitter
(``matrx-codex-plugin/hooks/emit.py``) run over a real directory tree — one
``UserPromptSubmit``, a file written into ``notes/``, a second file written
inside a nested git checkout, then a real ``Stop`` payload — with only the
session's ``cwd`` rewritten to the fixture root. Its ``refused``
``repository_subtrees_refused: 1`` is the producer's own count of the checkout
it refused to enter. If the two sides' format ever diverges, these tests go
red.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.services.coding_sessions.artifacts import MANIFEST_NAME, CodingSessionArtifactsLane
from app.services.coding_sessions.codex_writes import (
    PLUGIN_DECLARATION_SCHEMA,
    CodexRolloutSessionSource,
    plugin_declaration_files,
    read_plugin_declaration,
)
from app.services.local_db.database import LocalDatabase
from tests.unit.test_codex_artifact_source import _FakeFilesClient

pytestmark = pytest.mark.anyio

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "codex"
DECLARATION = FIXTURES / "hook-declaration.writes.json"
WITH_WRITES = FIXTURES / "session-with-writes.jsonl"
FIXTURE_CWD = "/Users/fixture/code/demo-repo"
# The identity inside the real rollout fixture, and the one file its patches
# write inside the session cwd.
SESSION_WITH_WRITES = "019f94a6-dd83-71f0-aee4-4456aff06c27"
ROLLOUT_WRITTEN_REL = "scripts/sync-types.mjs"
DECLARED_REL = "notes/release-notes.md"
#: The installed plugin id today. The source globs it, so a differently-named
#: install is still read instead of quietly showing an empty panel.
PLUGIN_ID = "matrx-codex-plugin-ai-matrx"


def _plant_declaration(home: Path, cwd: Path, *, session_id: str | None = None, plugin_id: str = PLUGIN_ID) -> Path:
    """Copy the real emitter's output into a private CODEX_HOME, re-rooted."""
    record = json.loads(DECLARATION.read_text().replace(FIXTURE_CWD, str(cwd)))
    if session_id is not None:
        record["session_id"] = session_id
    target = (
        home / "plugins" / "data" / plugin_id / "coding-session-bridge" / "writes"
        / f"{record['session_id']}.writes.json"
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(record))
    return target


def _rehome_rollout(home: Path, cwd: Path) -> Path:
    target = home / "sessions" / "2026" / "07" / "24" / f"rollout-{WITH_WRITES.stem}.jsonl"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(WITH_WRITES.read_text().replace(FIXTURE_CWD, str(cwd)))
    return target


def _workspace(tmp_path: Path) -> Path:
    """A session cwd that is NOT a checkout, holding both written files."""
    work = tmp_path / "work"
    (work / "notes").mkdir(parents=True)
    (work / "notes" / "release-notes.md").write_text("# Release notes\n\nGenerated by a Codex turn.\n")
    (work / "scripts").mkdir()
    (work / "scripts" / "sync-types.mjs").write_text("export default 1;\n")
    return work


# --------------------------------------------------------------------------
# Reading a declaration
# --------------------------------------------------------------------------


def test_the_real_emitters_declaration_is_read_with_its_paths_and_its_refusals(tmp_path: Path) -> None:
    home = tmp_path / "codex-home"
    work = _workspace(tmp_path)
    path = _plant_declaration(home, work)

    found, available = plugin_declaration_files(home)
    assert found == [path]
    assert available == 1

    declaration = read_plugin_declaration(path)
    assert declaration is not None
    assert declaration.session_id == SESSION_WITH_WRITES
    assert declaration.cwd == work
    assert declaration.written == (work / DECLARED_REL,)
    # The producer's own count of what THE REPOSITORY RULE refused.
    assert declaration.refused["repository_subtrees_refused"] == 1
    assert declaration.turns_scanned == 1


def test_a_declaration_from_a_future_plugin_is_refused_not_guessed_at(tmp_path: Path) -> None:
    """A later plugin could mean something else by the same key, and a wrong
    guess here uploads the wrong files."""
    home = tmp_path / "codex-home"
    path = _plant_declaration(home, _workspace(tmp_path))
    record = json.loads(path.read_text())
    record["schema_version"] = PLUGIN_DECLARATION_SCHEMA + 1
    path.write_text(json.dumps(record))
    assert read_plugin_declaration(path) is None


def test_a_declared_path_outside_the_session_cwd_is_counted_never_captured(tmp_path: Path) -> None:
    home = tmp_path / "codex-home"
    work = _workspace(tmp_path)
    elsewhere = tmp_path / "elsewhere" / "config.toml"
    elsewhere.parent.mkdir(parents=True)
    elsewhere.write_text("x = 1\n")
    path = _plant_declaration(home, work)
    record = json.loads(path.read_text())
    record["files"][str(elsewhere)] = {"path": str(elsewhere), "change": "created", "size": 6}
    path.write_text(json.dumps(record))

    declaration = read_plugin_declaration(path)
    assert declaration is not None
    assert declaration.written == (work / DECLARED_REL,)
    assert declaration.outside_cwd == (elsewhere,)


# --------------------------------------------------------------------------
# Discovery: two sources, one session
# --------------------------------------------------------------------------


def test_a_session_seen_by_both_sources_is_yielded_once_with_both_files(tmp_path: Path) -> None:
    home = tmp_path / "codex-home"
    work = _workspace(tmp_path)
    _rehome_rollout(home, work)
    _plant_declaration(home, work)

    discovered = list(CodexRolloutSessionSource(home=home).discover())
    assert [one.cli_session_id for one in discovered] == [SESSION_WITH_WRITES]
    session = discovered[0]
    assert session.files is not None
    assert set(session.files) == {work / ROLLOUT_WRITTEN_REL, work / DECLARED_REL}
    assert session.notes["hook_declared_writes"] == 1
    assert session.notes["attributed_writes"] == 1


def test_a_declaration_with_no_rollout_in_the_window_is_still_a_listed_session(tmp_path: Path) -> None:
    """The rollout scan is bounded and Codex archives old sessions. A turn's
    write record carries its own identity and cwd, so it needs no rollout."""
    home = tmp_path / "codex-home"
    work = _workspace(tmp_path)
    _plant_declaration(home, work, session_id="019ffffe-0000-7000-8000-00000000cs34")

    discovered = list(CodexRolloutSessionSource(home=home).discover())
    assert [one.cli_session_id for one in discovered] == ["019ffffe-0000-7000-8000-00000000cs34"]
    assert discovered[0].files == (work / DECLARED_REL,)
    assert discovered[0].root == work


def test_a_differently_named_plugin_install_is_still_read(tmp_path: Path) -> None:
    home = tmp_path / "codex-home"
    work = _workspace(tmp_path)
    _plant_declaration(home, work, session_id="019ffffe-0000-7000-8000-0000000alt01", plugin_id="matrx-codex-plugin")
    assert [one.cli_session_id for one in CodexRolloutSessionSource(home=home).discover()] == [
        "019ffffe-0000-7000-8000-0000000alt01"
    ]


def test_silence_from_the_hook_source_is_reported_as_its_own_fact(tmp_path: Path) -> None:
    """An absent plugin is a DIFFERENT fact from a plugin that ran and found
    nothing, and before this the screen could only talk about apply_patch —
    true, and useless to the person looking at an empty panel."""
    home = tmp_path / "codex-home"
    (home / "sessions").mkdir(parents=True)
    source = CodexRolloutSessionSource(home=home)
    list(source.discover())
    sentences = source.describe_gaps({})
    assert any("hook-time write record yet" in sentence for sentence in sentences)
    assert any("AI Matrx plugin for Codex" in sentence for sentence in sentences)

    _plant_declaration(home, _workspace(tmp_path))
    list(source.discover())
    after = source.describe_gaps({})
    assert any("have a hook-time write record naming 1 file(s)" in sentence for sentence in after)
    assert not any("hook-time write record yet" in sentence for sentence in after)
    # The producer's repository refusal reaches the person as a sentence.
    assert any(
        "inside a git checkout and are deliberately not captured" in sentence for sentence in after
    )


# --------------------------------------------------------------------------
# End to end: the lane captures it, with the repository rule intact
# --------------------------------------------------------------------------


async def test_the_lane_captures_a_hook_declared_file_and_still_refuses_a_checkout(tmp_path: Path) -> None:
    home = tmp_path / "codex-home"
    work = _workspace(tmp_path)
    # A second declared path that lives inside a checkout. The producer would
    # never have declared it; the lane must refuse it anyway, because an
    # explicit file list is not a second door into the upload with the rule
    # switched off.
    checkout = work / "vendored-repo"
    (checkout / ".git").mkdir(parents=True)
    source_file = checkout / "main.py"
    source_file.write_text("SECRET = 'never uploaded'\n")
    path = _plant_declaration(home, work)
    record = json.loads(path.read_text())
    record["files"][str(source_file)] = {"path": str(source_file), "change": "created", "size": 26}
    path.write_text(json.dumps(record))

    durable = tmp_path / "durable"
    db = LocalDatabase(tmp_path / "codex.db")
    await db.connect()
    lane = CodingSessionArtifactsLane(
        db=db,
        provider="codex",
        source=CodexRolloutSessionSource(home=home),
        durable_root=durable,
        files_client=_FakeFilesClient(),  # type: ignore[arg-type]
        cloud_enabled=False,
    )
    try:
        tick = await lane.run_once()
    finally:
        await db.close()
    assert tick["captured"] >= 1

    session_dir = durable / SESSION_WITH_WRITES
    kept = sorted(
        p.relative_to(session_dir).as_posix()
        for p in session_dir.rglob("*")
        if p.is_file() and p.name != MANIFEST_NAME
    )
    assert kept == [DECLARED_REL]
    manifest = json.loads((session_dir / MANIFEST_NAME).read_text())
    assert "never uploaded" not in json.dumps(manifest)
    assert "main.py" not in json.dumps(manifest)
